# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 99024f76ee5709060c9674fd3d587b311d93dbda125ab7fb74d48728de1aea003febb25f23390354e87fa0c42496c469049916157cb97e679b23c9e07ff7a3df

test:
  secret_key_base: 40d3c4b939ad5c0b64b8b24154a057150eb65e14ab056dee3583ed1eb0e2fb85bc1bad3035cc0b3cc4a738a71afa63741ebe311e861fa0bbe63f00868282d1ff

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
